### ISSUE TITLE
Fix Eclair API

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/BTCPayServer.Lightning#22] opened 2019-10-07 16:44 UTC
According to @araspitzu the eclair api has changed again and we need to fix before we can support it fully in btcpay

**Comment by araspitzu** [comment] 2019-10-24 15:26
Yes payment APIs changed with https://github.com/ACINQ/eclair/pull/1130, this mostly touched the way we represent payment internally but i'm not sure to what extent you used the payment data in btcpay. As an example the  [`/getsentinfo`](https://acinq.github.io/eclair/#getsentinfo) is used to check if a payment has been finalized now returns more data, likewise does /getreceivedinfo. Note the "status" field now is not just a string but an object.

**Comment by araspitzu** [comment] 2019-10-24 15:39
Is there a way i can run integration tests on this?

**Comment by Kukks** [comment] 2019-10-24 15:43
you'll need dotnet and docker compose installed installed 

I think this should do it:
```sh
cd tests
docker-compose up
cd ../ 
dotnet test 
```

**Comment by araspitzu** [comment] 2019-10-25 09:58
Not much but i can reproduce the expected errors in the tests, namely it returns:
```
   at BTCPayServer.Lightning.Tests.CommonTests.CanPayInvoiceAndReceive() in /home/andrea/workspace/BTCPayServer.Lightning/tests/CommonTests.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
Test run in progress.Unexpected character encountered while parsing value: {. Path '[0].status', line 1, position 968.                                                       
```
and is coming from:
```
   at BTCPayServer.Lightning.Eclair.EclairClient.SendCommandAsync[TRequest,TResponse](String method, TRequest data, CancellationToken cts) in /home/andrea/workspace/BTCPayServer.Lightning/src/BTCPayServer.Lightning.Eclair/EclairClient.cs:line 345
   at BTCPayServer.Lightning.Eclair.EclairClient.GetSentInfo(String paymentHash, String id, CancellationToken cts) in /home/andrea/workspace/BTCPayServer.Lightning/src/BTCPayServer.Lightning.Eclair/EclairClient.cs:line 198
   at BTCPayServer.Lightning.Eclair.EclairLightningClient.Pay(String bolt11, CancellationToken cancellation) in /home/andrea/workspace/BTCPayServer.Lightning/src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs:line 127
```
Indeed the `/getsentinfo` new returns an object in the status field. Without further ado I'll try to make a fix although my C# skills are pretty much close to zero :smile:

**Comment by Kukks** [comment] 2019-10-25 10:08
perfect bait to lure you to our world :D

**Comment by NicolasDorier** [comment] 2019-11-01 07:17
Ping @araspitzu  I took a look. The problem is that for some reason Eclair is not sending back proper HTTP on the port for a while, then suddenly start doing so after 2-3 minutes.

**Comment by NicolasDorier** [comment] 2019-11-01 08:01
@araspitzu I fixed all the tests. You probably broke the API because the code was pretty far of from what the API was sending us now. Be careful in the future as people depend on it, we might not be able to fix it by ourselves.

**Comment by NicolasDorier** [comment] 2019-11-01 08:04
I bumped the library package. We will need new version of BTCPayServer to test eclair again.

**Comment by araspitzu** [comment] 2019-11-04 08:48
@NicolasDorier hey thanks for the fixes, unfortunately the API changes were breaking but also  preparation work for AMP. I suspect the 2-3 min of delay is because the HTTP API is one of the last thing that is created during the bootstrap and it does take a bit of time.

**Comment by NicolasDorier** [comment] 2019-11-04 11:26
@araspitzu can you returns a proper error in this case so maybe I can just make the API try again soon?

**Comment by araspitzu** [comment] 2019-11-04 11:43
I'm not sure if that would work, as soon as eclair binds to the interface the API is ready to reply and errors are handled in the "standard" way (i.e HTTP 500). Probably it's worth to investigate if the 2-3 min is caused by a startup delay of the whole application or is specific to the API, i know we start the APIs close to the end of the bootstrap but it shouldn't take 3 minutes in normal conditions. I'll try to reproduce this with `cd tests && docker-compose up -d && dotnet test`

**Comment by NicolasDorier** [comment] 2019-11-04 12:21
@araspitzu I will check again, but I am pretty sure it was not throwing HTTP 500 but rubish bytes.

**Comment by NicolasDorier** [comment] 2019-11-04 12:22
btw, btcpayserver got updated with the working version of the API so if you want ot rebase and retest the eclair PR in btcpayserver-docker it should work.

**Comment by NicolasDorier** [comment] 2019-11-04 12:28
@araspitzu also do you have good settings to set for tests environment? Things like gossiping fast without waiting forever or things like this?

**Comment by NicolasDorier** [comment] 2019-11-04 12:37
@araspitzu checked again, it accepts connection but does not reply http 500. It would be useful if it did, is it something you can do?

**Comment by araspitzu** [comment] 2019-11-04 15:30
There isn't an option to do fast gossiping but maybe [`mindepth-blocks`](https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/resources/reference.conf#L60) can be helpful here, it sets the number of blocks that will be considered enough before the channel can be used, by default this is 3 blocks. I can't reproduce the HTTP API not replying for 2-3 minutes, i reverted commit 53abd5c and run the test (again via `cd tests && docker-compose up -d && dotnet test`) with following results:
- test suite is stuck 
- both eclair instances are immediately reachable via API, both `test_eclair_1` and `test_eclair_dest_1` replied correctly to `eclair-cli -p bukkake -a 127.0.0.1:4571 getinfo`

**Comment by NicolasDorier** [comment] 2019-11-05 03:36
@araspitzu test hanging is good. It means the HTTP is replying correctly, before that it would crash.

**Comment by NicolasDorier** [comment] 2019-11-05 04:40
omg, checking Eclair is taking more than 2 min just to start accepting proper request to the API. Wtf it is doing for all this time?

**Comment by NicolasDorier** [comment] 2019-11-05 04:42
ah ok... it is failing because bitcoind is "synching" while it is not.

**Comment by NicolasDorier** [comment] 2019-11-05 04:45
Ah no it is really taking 2 minutes to boot...

**Comment by NicolasDorier** [comment] 2019-11-05 05:12
Closing this, fixed the remaining problems.

**Closed by NicolasDorier** 2019-11-05 05:12 UTC
